pipeline{
    agent none
    stages{
        stage('build')
        {
            steps
            {
                echo "this is the build stage" 
            }
        }
        stage('test')
        {
            steps
            {
                echo "this is the test stage"
            }
        }
        stage('deploy')
        {
        steps
        {
            echo "this is the deploy stage"
        }
        }

    }
}